config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dice_pools#index', as: 'roller'
  get 'gm', to: 'dice_pools#gm_index', as: 'dm_roller'
  post 'roll.js', to: 'dice_pools#roll'

  mount ActionCable.server => '/cable'
end

app/models/dice_pool.rb
# frozen_string_literal: true

# Handles Results for rolls
class DicePool
  extend ActiveModel::Callbacks
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Conversion
  include ActiveModel::Dirty
  include ActiveModel::Model
  include ActiveModel::Serializers::JSON
  include ActiveModel::Validations

  DEFAULT_ROLLER = 'Anon'
  DEFAULT_PURPOSE = 'N/A'
  DNR_SEQUENCE = /^dnr(?!\w):?\s*/i.freeze
  NAME_MAX_LENGTH = 10
  PURPOSE_MAX_LENGTH = 300

  define_attribute_methods :roller, :dice, :purpose, :result
  attr_accessor :roller, :dice, :purpose
  attr_reader :result

  validates :roller, presence: true, length: {
    in: 2...NAME_MAX_LENGTH,
    message: 'Must have a roller name (Maximum: 10).'
  }
  validates :dice, allow_nil: false, length: {
    minimum: 1, message: 'Must have dice to roll.'
  }
  validates :purpose, presence: true, length: {
    in: 2...PURPOSE_MAX_LENGTH,
    message: 'Must have a purpose (Maximum: 300).'
  }

  define_model_callbacks :initialize, only: :after
  after_initialize :set_default_values

  def initialize(attributes = nil)
    super(attributes)

    run_callbacks(:initialize) {}
  end

  def persisted?
    false
  end

  def id
    nil
  end

  def as_json
    { roller: roller, purpose: purpose, json_dice: json_dice }.to_json
  end

  def attributes=(hash)
    hash.symbolize_keys!

    hash.each { |key, value| send("#{key}=", value) }
  end

  # Gives a pretty readable string to print this instance
  def to_s
    "#<#{self.class} " +
      [
        "roller: #{roller}",
        "purpose: #{purpose[0..20]}",
        ("result: #{result}" if result),
        "dice: #{dice.transform_keys.map(&:to_s)}"
      ].reject(&:blank?).join(', ') + '>'
  end

  # Rolls the entire dice pool and tallies the result
  def roll
    return false unless valid?

    dice.each_key { |die| roll_die(die) }
    sum_result
    DicePoolBroadcastJob.perform_later result_json

    result
  end

  def result_json
    return nil unless result

    {
      roller: roller,
      purpose: purpose,
      results: {
        dice: json_dice_results,
        pool: json_pool_results
      }.to_json
    }
  end

  # Loads dice from a map of dice names to dice counts
  def json_dice=(dice_json)
    @dice = JSON.parse(dice_json).transform_keys do |die_name|
      Die.find_by(name: die_name.to_sym)
    end
  end

  # a map of dice names to dice counts
  def json_dice
    dice.transform_keys(&:name).to_json
  end

  def json_pool_results
    result.stringify_keys.to_json
  end

  def json_dice_results
    dice.map do |die, die_results|
      [die.name.to_s, die_results.map(&:displayable_results)]
    end.to_h.to_json
  end

  private

  attr_writer :result

  def roll_die(die)
    rolls = []
    dice[die].times do
      rolls << die.roll
    end

    dice[die] = rolls
  end

  def sum_result
    self.result = dice.values.flatten.sum.finalize
  end

  def update(params)
    params.each do |key, value|
      send("#{key}=", value)
    end
  end

  def set_default_values
    self.roller ||= 'Anon'
    self.purpose ||= 'N/A'
    self.dice ||= {}
  end
end

app/controllers/dice_pools_controller.rb
class DicePoolsController < ApplicationController
  class << self
    RENDER_TEMPLATE_MATCH = /^render_(\w*)_template$/.freeze

    def method_missing(name, *args, &block)
      if (template = fetch_template(name))
        return template
      end

      super
    end

    def fetch_template(name)
      if name.to_s.match(RENDER_TEMPLATE_MATCH)
        return render partial: "templates/#{Regexp.last_match(1)}"
      end

      false
    rescue ActionView::MissingTemplate
      false
    end

    def respond_to_missing?(method, *)
      method.to_s.match?(RENDER_TEMPLATE_MATCH) || super
    end
  end


  # GET /index
  def index
    @dice_pool = fetch_dice_pool

    render layout: 'index'
  end

  # GET /gm
  alias gm_index index

  # POST /index
  def roll
    @dice_pool = DicePool.new(dice_pool_params)
    cookies[:dice_pool] = @dice_pool.as_json

    handle_roll
  end

  private

  def fetch_dice_pool
    return DicePool.new unless cookies[:dice_pool].present?

    DicePool.new.from_json(cookies[:dice_pool])
  end

  # Never trust parameters; only allow the white list.
  def dice_pool_params
    params.require(:dice_pool)
          .permit(:roller, :purpose, :result, :rolled, :json_dice)
  end

  def handle_roll
    @dice_pool.validate!
    @dice_pool.roll

    render json: {
      pool: @dice_pool.json_pool_results,
      dice: @dice_pool.json_dice_results
    }
  rescue ActiveModel::ValidationError
    render json: { message: @dice_pool.errors.values.flatten.join(' ') },
           status: 422
  end
end

app/helpers/dice_pools_helper.rb
module DicePoolsHelper
  def parse_die_result(die_results)
    die_results = die_results.to_a.map do |die_result|
      parse_result(*die_result, 'die')
    end.join.html_safe

    die_results.empty? ? blank_result_tag('die') : die_results
  end

  def parse_results(results)
    results = results.map { |result| parse_result(*result) }.join.html_safe

    results.empty? ? '<div class="result blank"></div>'.html_safe : results
  end

  private

  def parse_result(result_type, result_type_count, type = '')
    die_html = "<div class='#{[type, 'result'].reject(&:blank?).join('-')} " \
      "#{result_type}'></div>"
    Array.new(result_type_count, die_html).join.html_safe
  end

  def blank_result_tag(type = '')
    "<div class='#{[type, 'result'].reject(&:blank?).join('-')} " \
      "blank'></div>".html_safe
  end
end

app/views/dice_pools/_details.html.erb
<div id='details' hidden>
  <div class='screencover'></div>
  <div class='popup'>
    <div class='block-field'>
      <%= form.label :name %>
      <%= form.text_field :roller, id: :dice_pool_roller %>
    </div>

    <div class='block-field' hidden>
      <%= form.label :purpose %>
      <%= form.text_area :purpose, id: :dice_pool_purpose %>
    </div>

    <div class='block-field'>
      <%= form.label :purpose %>
      <%= form.text_area :shadow_purpose, id: :dice_pool_shadow_purpose %>
    </div>

    <div class='nav-line'>
      <div class='nav-table'>
        <%= nav_button_cell 'roll', 'roll' %>
      </div>
    </div>
  </div>
</div>

app/views/dice_pools/_dice_selection.html.erb
<div class='dice-selection'>
    <% DieTypes::PAIRS.each do |group| %>
    <div class='group'>
      <% group.each do |die_type| %>
        <% next unless die_type %>
        <div class='dice <%= die_type %>' data-die-name='<%= die_type %>'>
          <div class='die <%= die_type %> faded'></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="block-field" hidden>
  <%= form.text_field :json_dice, id: :dice_pool_dice %>
</div>

app/views/dice_pools/_info.html.erb
<div id='info' class='page openable closed'>
  <h4 class='page-title'>How to Use</h4>

  <%# General %>
  <div>
    <h5>Purpose</h5>
    <p>The roller can be used by groups to roll dice together.</p>
  </div>

  <%# Roller %>
  <div>
    <h5>Roller <%= die_icon = nav_icon('roll') %></h5>
    <p>Select the dice pool and click the <%= die_icon %> to roll.</p>
    <p>Fill in purpose and name to inform the DM of the roll's intent.</p>
    <p>
      Name: Your name. Used for the group to identify you.
      <%= DicePool::NAME_MAX_LENGTH %> characters max.
    </p>
    <p>
      Purpose: Your purpose for a given roll. Used for the DM to know what you
      wanted from the roll. <%= DicePool::PURPOSE_MAX_LENGTH %> characters max.
    </p>
    <p>
      <span class='important'>DNR: </span>
      Put &ldquo;dnr&rdquo; or &ldquo;dnr:&rdquo; at the front of
      the purpose to hide from your party members. Not hidden from the GM.
    </p>
  </div>

  <%# Index %>
  <div>
    <h5>Rolls Index <%= nav_icon('index') %></h5>
    <p>Shows roll results for the group.</p>
    <p>Click on a purpose with &ldquo;...&rdquo; to expand.</p>
  </div>

  <% if params[:action].eql? 'index' %>
    <%# GMs %>
    <div>
      <h5>GMs</h5>
      <p>Hidden rolls are available <a href='/gm'>here</a>.</p>
      <p>In the GM page, all rolls, including hidden rolls are shown.</p>
      <p>GM only, please.</p>
    </div>
  <% else %>
    <%# Players %>
    <div>
      <h5>Players</h5>
      <p>Players should roll <a href='/'>here</a>.</p>
    </div>
  <% end %>
</div>

app/views/dice_pools/_nav.html.erb
<%= hrule if sticky.eql?('bottom') %>

<div <%= sticky ? "id='#{sticky}-nav'" : '' %> class='nav-bar<%= sticky ? ' ' + sticky : ''%>'>
  <div class='nav-table base'>
    <%= nav_button_cell('page', 'info', data: { page: 'info' }) %>
    <%= nav_button_cell('page roll-details', 'roll', data: { page: 'roller' }) %>
    <%= nav_button_cell('page', 'index', data: { page: 'rolls' }) %>
  </div>
</div>

<%= hrule if sticky.eql?('top') %>

app/views/dice_pools/_roller.html.erb
<div id='roller' class='page openable open'>
  <p id='notice'><p>


  <div id='results'>
    <%= render 'templates/dice_results' %>
    <%= hrule(margin: '0.5em 0') %>
    <%= render 'templates/pool_results' %>
  </div>
  <%= hrule(margin: '0.5em 0') %>

  <div id='dice-pool'>
    <%= form_with(url: roller_url, model: @dice_pool, local: true, id: 'roller-form') do |form| %>
      <%= render 'details', form: form %>
      <%= render 'dice_selection', form: form %>
    <% end %>
  </div>
</div>

app/views/dice_pools/_rolls.html.erb
 <div id='rolls'>
  <h1>Rolls</h1>

  <table>
    <tbody id='dice-pools'></tbody>
  </table>
</div>

app/views/dice_pools/gm_index.html.erb
<%= render file: 'dice_pools/index' %>

app/views/dice_pools/index.html.erb
<%= render 'nav', sticky: 'top' %>

<%= render 'info' %>
<%= render 'roller' %>
<%= render 'rolls' %>

<%= render 'nav', sticky: 'bottom' %>